#Author : Saranraj
#version : 0.1 dev
#company : Presidio
name: selfHostedRunner
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
workflow_dispatch:
   inputs:
     TF_ACTION:
       description:              'Plan (review, correct errors, plan again) then Apply'
       type:                     choice
       options:
         - 'Plan'
         - 'Apply'
       default:                  'Plan'
     TF_LOG_LEVEL:
       description:              'Self-hosted runner Terraform global log level (includes both core and provider if set):'
       type:                     choice
       options:
         - 'default'
         - 'INFO'
         - 'WARN'
         - 'ERROR'
env:
 TF_INSTANCED:                   "shrisaranraj"
 TF_ACTION:                      ${{ github.event.inputs.TF_ACTION }}
 SHR_S:                          "./${{ github.event.inputs.TF_INSTANCED }}/.data/scripts/"
 permissions:                      write-all
jobs:
 run_ghr_job:
   name:                       Github Hosted Runner Job
   runs-on:                      ubuntu-latest
   environment:                  Prod
   outputs:
     nowdvar:                    ${{ steps.envsetup.outputs.nowdvar }}
     nowvar:                     ${{ steps.envsetup.outputs.nowvar }}
     logdirpath:                 ${{ steps.envsetup.outputs.logdirpath }}
     tfversion:                  ${{ steps.envsetup.outputs.tfversion }}
     runnerversion:              ${{ steps.envsetup.outputs.runnerversion }}
     azurermversion:             ${{ steps.envsetup.outputs.azurermversion }}
     azureadversion:             ${{ steps.envsetup.outputs.azureadversion }}
     runnerna:                   ${{ steps.envsetup.outputs.runnern }}
     runnerhna:                  ${{ steps.envsetup.outputs.runnerhn }}
     rgfull:                     ${{ steps.envsetup.outputs.rgfull }}
     ghorg:                      ${{ steps.envsetup.outputs.ghorg }}
     shrlogpath:                 ${{ steps.envsetup.outputs.shrlogpath }}
     logzipfile:                 ${{ steps.envsetup.outputs.logzipfile }}
     tokenfail:                  ${{ steps.getregtoken.outputs.tokenfail }}
     deployfail:                 ${{ steps.ghr_job.outputs.deployfail }}
     tfloglevel:                 ${{ steps.envsetup.outputs.tfloglevel }}
   steps:
     - name:                     'Az CLI login'
       uses:                     Azure/login@v1.4.3
       with:
         client-id:              ${{ secrets.CLIENTID}}
         tenant-id:              ${{ secrets.TENANTID}}
         subscription-id:        ${{ secrets.SUBSCRIPTIONID }}
         allow-no-subscriptions: true
if: |
         !cancelled()
         - name:                     'Set Subscription'
run: |
         az account set --subscription="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
       if: |
         !cancelled()
