name: SelfHostedVM
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
     - name:                     'Az CLI login'
       uses:                     Azure/login@v1.4.3
       with:
         client-id:              ${{ secrets.CLIENTID}}
         tenant-id:              ${{ secrets.TENANTID}}
         subscription-id:        ${{ secrets.SUBSCRIPTIONID }}
         allow-no-subscriptions: true
env:
 TF_INSTANCED:                   "shrisaranraj"
 TF_ACTION:                      ${{ github.event.inputs.TF_ACTION }}
 SHR_S:                          "./${{ github.event.inputs.TF_INSTANCED }}/.data/scripts/"
 permissions:                      write-all

run:
         az account set --subscription="${{ secrets.SUBSCRIPTIONID }}"
